/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class fr_linkit_engine_internal_manipulation_invokation_ObjectInvocator */

#ifndef _Included_fr_linkit_engine_internal_manipulation_invokation_ObjectInvocator
#define _Included_fr_linkit_engine_internal_manipulation_invokation_ObjectInvocator
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     fr_linkit_engine_internal_manipulation_invokation_ObjectInvocator
 * Method:    invokeMethod0
 * Signature: (Ljava/lang/Object;Ljava/lang/String;Ljava/lang/String;[BB[Ljava/lang/Object;)Ljava/lang/Object;
 */
extern "C" JNIEXPORT jobject JNICALL Java_fr_linkit_engine_internal_manipulation_invokation_ObjectInvocator_invokeMethod0
(JNIEnv*, jclass, jobject, jstring, jstring, jbyteArray, jbyte, jobjectArray);

#ifdef __cplusplus
}
#endif
#endif
