/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class fr_linkit_engine_internal_utils_NativeUtils */

#ifndef _Included_fr_linkit_engine_internal_utils_NativeUtils
#define _Included_fr_linkit_engine_internal_utils_NativeUtils
#ifdef __cplusplus

extern "C" {
#endif
/*
 * Class:     fr_linkit_engine_internal_utils_NativeUtils
 * Method:    callConstructor
 * Signature: (Ljava/lang/Object;Ljava/lang/String;[Ljava/lang/Object;)V
 */
JNIEXPORT void JNICALL Java_fr_linkit_engine_internal_utils_NativeUtils_callConstructor
  (JNIEnv *, jclass, jobject, jstring, jobjectArray);

/*
 * Class:     fr_linkit_engine_internal_utils_NativeUtils
 * Method:    allocate
 * Signature: ([Ljava/lang/Class;)Object
 */
JNIEXPORT jobject JNICALL Java_fr_linkit_engine_internal_utils_NativeUtils_allocate
	(JNIEnv*, jclass, jclass);

#ifdef __cplusplus
}
#endif
#endif
