/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class fr_linkit_engine_test_natives_NativeTests */

#ifndef _Included_fr_linkit_engine_test_natives_NativeTests
#define _Included_fr_linkit_engine_test_natives_NativeTests
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     fr_linkit_engine_test_natives_NativeTests
 * Method:    makePrint
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_fr_linkit_engine_test_natives_NativeTests_makePrint
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
